### ISSUE TITLE
Install doesn't honour CMAKE_INSTALL_PREFIX

### ISSUE THREAD

**Issue by fnoop** [MonashUAS/cmavnode#25]
Instead is currently hardcoded for /opt directory.

**Comment by JMare** [comment]
Yes good point, this is not good I will fix soon

⁣Sent from BlueMail ​

**Comment by fnoop** [comment]
Thanks :)

I just changed the install lines to:
```
install(TARGETS cmavnode DESTINATION bin)
install(DIRECTORY DESTINATION log)
install(FILES log.conf DESTINATION etc)
```

This honours -DCMAKE_INSTALL_PREFIX otherwise installs to /usr/local
