### ISSUE TITLE
log.conf must be in cwd

### ISSUE THREAD

**Issue by fnoop** [MonashUAS/cmavnode#26]
ASSERTION FAILURE FROM EASYLOGGING++ (LINE: 5871) [gcfStream.is_open()] WITH MESSAGE "Unable to open global configuration file [log.conf] for parsing."

log.conf must be in the current directory, even if calling cmavnode from another directory.  eg.:
etc/log.conf
bin/cmavnode
It's fine to start from etc directory with ../bin/cmavnode
Not Ok to start anywhere else.

This should be configurable.

**Comment by JMare** [comment]
Do you think logging to file is valuable for program such as this? I thought it would be useful originally but i have never really had a need to look at the logs, and if starting with upstart/systemd you get logs through that anyway, so i was considering removing easylogging.

At the very least it should be disabled by default and enabled by a command line flag or config file.
Thanks for raising issues its good to have other peoples thoughts on it!

**Comment by fnoop** [comment]
Logging would be really useful it if contained mavlink messages.  For example mavproxy outputs to stdout/console any received mavlink messages so you get versions, status, important messages etc.  This is really useful as reference.

**Comment by JMare** [comment]
For now I have removed logging, logging all mavlink messages would be a different thing entirely and could be implemented easily.

This is just removing the logs of cmavnode stdout/stderr.
