### ISSUE TITLE
01 SYSID and 01 COMPONENT ID crash cmavnode

### ISSUE THREAD

**Issue by roque-canales** [MonashUAS/cmavnode#32]
Hello I attempt to use cmavnode with software that always send 01 for sysID and 01 for compID.

As soon as cmavnode receive this packet, it scratch and no work until reboot raspi.

Could you please tell me what I can do for get arrond this issue?

**Comment by JMare** [comment]
Strange. Never seen this before, I don't have this issue on Rpi.
Make sure you are on master branch as there was an old bug that caused lockup on rpi.

Can you show your config file and give some more information about how you have it setup, i can try to replicate it.

**Comment by JMare** [comment]
Unable to replicate, if I have more information I can look into this.
