### ISSUE TITLE
trying to build on raspberry pi...make gives an error

### ISSUE THREAD

**Issue by mahdi-nasehiyan** [MonashUAS/cmavnode#36]
hi
i'm trying to build cmavnode on a RPi1 B+ running raspbian stretch.
when i execut `make`(after successfully executing `cmake ..`) it shows this error:

[ 14%] Building CXX object CMakeFiles/cmavnode.dir/src/asyncsocket.cpp.o
In file included from /home/pi/Desktop/cmavnode-0.2.0/src/asyncsocket.h:15:0,
                 from /home/pi/Desktop/cmavnode-0.2.0/src/asyncsocket.cpp:8:
/home/pi/Desktop/cmavnode-0.2.0/src/mlink.h:17:55: fatal error: ../include/mavlink2/ardupilotmega/mavlink.h: No such file or directory
 #include "../include/mavlink2/ardupilotmega/mavlink.h"
                                                       ^
compilation terminated.
CMakeFiles/cmavnode.dir/build.make:62: recipe for target 'CMakeFiles/cmavnode.dir/src/asyncsocket.cpp.o' failed
make[2]: *** [CMakeFiles/cmavnode.dir/src/asyncsocket.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/cmavnode.dir/all' failed
make[1]: *** [CMakeFiles/cmavnode.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by JMare** [comment]
You need to run git submodule update --init

**Comment by mahdi-nasehiyan** [comment]
thanks. i'll give it a try!
sorry for not properly reading the instructions:)

**Comment by mahdi-nasehiyan** [comment]
ok that error is gone.
now `make` shows another error:

[ 14%] Building CXX object CMakeFiles/cmavnode.dir/src/asyncsocket.cpp.o
/tmp/cc4ZxGa9.s: Assembler messages:
/tmp/cc4ZxGa9.s: Fatal error: can't write 352 bytes to section .text._ZN5boost9date_time14microsec_clockINS_10posix_time5ptimeEE11create_timeEPFP2tmPKlS6_E of CMakeFiles/cmavnode.dir/src/asyncsocket.cpp.o because: 'No space left on device'
/tmp/cc4ZxGa9.s: Fatal error: can't close CMakeFiles/cmavnode.dir/src/asyncsocket.cpp.o: No space left on device
CMakeFiles/cmavnode.dir/build.make:62: recipe for target 'CMakeFiles/cmavnode.dir/src/asyncsocket.cpp.o' failed
make[2]: *** [CMakeFiles/cmavnode.dir/src/asyncsocket.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/cmavnode.dir/all' failed
make[1]: *** [CMakeFiles/cmavnode.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by mahdi-nasehiyan** [comment]
oooh!
i tried `sudo make` and it's all good now...
hope there will be no more errors ...

**Comment by edd5750** [comment]
Hey, I'm trying to build cmavnode on a raspberry pi zero w, and I got stuck at _cmake .._ command. 
This error shows up 

-- Boost version: 1.62.0
-- Found the following Boost libraries:
--   program_options
--   thread
--   system
--   chrono
--   date_time
--   atomic
CMake Error at CMakeLists.txt:17 (find_package):
  By not providing "FindReadline.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Readline",
  but CMake did not find one.

  Could not find a package configuration file provided by "Readline" with any
  of the following names:

    ReadlineConfig.cmake
    readline-config.cmake

  Add the installation prefix of "Readline" to CMAKE_PREFIX_PATH or set
  "Readline_DIR" to a directory containing one of the above files.  If
  "Readline" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!
See also "/home/pi/cmavnode/CMakeFiles/CMakeOutput.log".
See also "/home/pi/cmavnode/CMakeFiles/CMakeError.log".

Any idea how to resolve this?

**Comment by JMare** [comment]
Closed as problem resolved
